#!/usr/bin/env python3
"""
Generate C++ header with pre-computed gamut transform matrices
and verify log curve parameters.

Uses colour-science to compute ProPhoto RGB → Target Gamut matrices.
Output: include/raw_alchemy/color_data.h
"""

import colour
import numpy as np
import os

# ============================================================
#  Configuration (matches Raw-Alchemy config.py)
# ============================================================
LOG_TO_WORKING_SPACE = {
    'F-Log': 'F-Gamut',
    'F-Log2': 'F-Gamut',
    'F-Log2C': 'F-Gamut C',
    'V-Log': 'V-Gamut',
    'N-Log': 'N-Gamut',
    'L-Log': 'ITU-R BT.2020',
    'Canon Log 2': 'Cinema Gamut',
    'Canon Log 3': 'Cinema Gamut',
    'S-Log3': 'S-Gamut3',
    'S-Log3.Cine': 'S-Gamut3.Cine',
    'Arri LogC3': 'ARRI Wide Gamut 3',
    'Arri LogC4': 'ARRI Wide Gamut 4',
    'Log3G10': 'REDWideGamutRGB',
    'D-Log': 'DJI D-Gamut',
}

LOG_ENCODING_MAP = {
    'S-Log3.Cine': 'S-Log3',
    'F-Log2C': 'F-Log2',
}

SOURCE_CS = 'ProPhoto RGB'


def compute_all_matrices():
    """Compute all ProPhoto → Target gamut conversion matrices."""
    source = colour.RGB_COLOURSPACES[SOURCE_CS]
    # De-duplicate: multiple log spaces may share the same gamut
    unique_gamuts = {}
    for log_name, gamut_name in LOG_TO_WORKING_SPACE.items():
        if gamut_name not in unique_gamuts:
            unique_gamuts[gamut_name] = []

    results = {}
    for gamut_name in unique_gamuts:
        target = colour.RGB_COLOURSPACES[gamut_name]
        M = colour.matrix_RGB_to_RGB(source, target)
        results[gamut_name] = M
        print(f"  {SOURCE_CS} -> {gamut_name}:")
        for row in M:
            print(f"    [{row[0]:12.8f}, {row[1]:12.8f}, {row[2]:12.8f}]")
        print()

    return results


def generate_cpp_header(matrices, output_path):
    """Generate C++ header file with pre-computed matrices."""

    lines = []
    lines.append("#pragma once")
    lines.append("/**")
    lines.append(" * @file color_data.h")
    lines.append(" * @brief Pre-computed color space data for Raw Alchemy C++.")
    lines.append(" *")
    lines.append(" * AUTO-GENERATED by scripts/gen_color_data.py — DO NOT EDIT.")
    lines.append(" * Gamut transform matrices: ProPhoto RGB -> Target Gamut (Linear)")
    lines.append(" * Computed using colour-science matrix_RGB_to_RGB() with CAT02 adaptation.")
    lines.append(" */")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cmath>")
    lines.append("#include <string>")
    lines.append("#include <unordered_map>")
    lines.append("")
    lines.append("namespace rawalchemy {")
    lines.append("")

    # --- Matrices ---
    lines.append("// ============================================")
    lines.append("//  Gamut Transform Matrices (3x3, row-major)")
    lines.append("//  Source: ProPhoto RGB (Linear)")
    lines.append("// ============================================")
    lines.append("")

    # Map gamut name to a valid C++ identifier
    gamut_to_id = {}
    for gamut_name in matrices:
        cpp_id = gamut_name.replace(' ', '_').replace('-', '_').replace('.', '_').replace('/', '_').replace('(', '').replace(')', '')
        gamut_to_id[gamut_name] = cpp_id

    for gamut_name, M in matrices.items():
        cpp_id = gamut_to_id[gamut_name]
        lines.append(f"// ProPhoto RGB -> {gamut_name}")
        lines.append(f"constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_{cpp_id.upper()} = {{{{")
        for row in M:
            lines.append(f"    {{{row[0]:12.8f}f, {row[1]:12.8f}f, {row[2]:12.8f}f}},")
        lines.append("}};")
        lines.append("")

    # --- Log space registry ---
    lines.append("// ============================================")
    lines.append("//  Log Space Registry")
    lines.append("//  Maps log space name -> {gamut_matrix, curve_name}")
    lines.append("// ============================================")
    lines.append("")

    lines.append("enum class LogCurve {")
    curve_names = set()
    for log_name in LOG_TO_WORKING_SPACE:
        curve = LOG_ENCODING_MAP.get(log_name, log_name)
        curve_names.add(curve)
    for i, cn in enumerate(sorted(curve_names)):
        cpp_cn = cn.replace(' ', '_').replace('-', '_').replace('.', '_')
        comma = "," if i < len(curve_names) - 1 else ""
        lines.append(f"    {cpp_cn}{comma}")
    lines.append("};")
    lines.append("")

    lines.append("struct LogSpaceInfo {")
    lines.append("    const std::array<std::array<float, 3>, 3>* gamutMatrix;")
    lines.append("    LogCurve curve;")
    lines.append("    const char* name;")
    lines.append("};")
    lines.append("")

    lines.append("// Lookup table: log space name -> info")
    lines.append("const std::unordered_map<std::string, LogSpaceInfo> LOG_SPACES = {")
    for log_name, gamut_name in LOG_TO_WORKING_SPACE.items():
        curve = LOG_ENCODING_MAP.get(log_name, log_name)
        gamut_id = gamut_to_id[gamut_name]
        curve_id = curve.replace(' ', '_').replace('-', '_').replace('.', '_')
        lines.append(f'    {{"{log_name}", {{&MAT_PROPHOTO_TO_{gamut_id.upper()}, LogCurve::{curve_id}, "{log_name}"}}}},')
    lines.append("};")
    lines.append("")

    # --- Log curve encoding functions ---
    lines.append("// ============================================")
    lines.append("//  Log Curve Encoding Functions (Linear -> Log)")
    lines.append("//  All operate on a single float value in [0, inf)")
    lines.append("// ============================================")
    lines.append("")

    lines.append("inline float logEncode(float x, LogCurve curve) {")
    lines.append("    switch (curve) {")

    # F-Log
    lines.append("    case LogCurve::F_Log: {")
    lines.append("        // F-Log: cut=0.00089, a=0.555556, b=0.009468, c=0.344676, d=0.790453, e=8.735631, f=0.092864")
    lines.append("        constexpr float cut = 0.00089f;")
    lines.append("        if (x < cut) return 8.735631f * x + 0.092864f;")
    lines.append("        return 0.344676f * std::log10(0.555556f * x + 0.009468f) + 0.790453f;")
    lines.append("    }")

    # F-Log2
    lines.append("    case LogCurve::F_Log2: {")
    lines.append("        // F-Log2: cut=0.000889, a=5.555556, b=0.064829, c=0.245281, d=0.384316, e=8.799461, f=0.092864")
    lines.append("        constexpr float cut = 0.000889f;")
    lines.append("        if (x < cut) return 8.799461f * x + 0.092864f;")
    lines.append("        return 0.245281f * std::log10(5.555556f * x + 0.064829f) + 0.384316f;")
    lines.append("    }")

    # V-Log
    lines.append("    case LogCurve::V_Log: {")
    lines.append("        // V-Log: cut=0.01, b=0.00873, c=0.241514, d=0.598206")
    lines.append("        if (x < 0.01f) return 5.6f * x + 0.125f;")
    lines.append("        return 0.241514f * std::log10(x + 0.00873f) + 0.598206f;")
    lines.append("    }")

    # N-Log
    lines.append("    case LogCurve::N_Log: {")
    lines.append("        // N-Log: a=650/1023, b=0.0075, c=150/1023, d=619/1023, cut=0.328")
    lines.append("        constexpr float a = 650.0f / 1023.0f;")
    lines.append("        constexpr float b = 0.0075f;")
    lines.append("        constexpr float c = 150.0f / 1023.0f;")
    lines.append("        constexpr float d = 619.0f / 1023.0f;")
    lines.append("        constexpr float cut = 0.328f;")
    lines.append("        if (x < cut) return a * std::cbrt(x + b);")
    lines.append("        return c * std::log(x) + d;")
    lines.append("    }")

    # Canon Log 2 (v1.2)
    lines.append("    case LogCurve::Canon_Log_2: {")
    lines.append("        // Canon Log 2 (v1.2): slope=0.24136077, offset=0.092864125, mult=87.09937546")
    lines.append("        constexpr float slope = 0.24136077f;")
    lines.append("        constexpr float offset = 0.092864125f;")
    lines.append("        constexpr float mult = 87.09937546f;")
    lines.append("        float s = x / 0.9f;  // reflection to scene-linear")
    lines.append("        if (s < 0.0f) return -slope * std::log10(-s * mult + 1.0f) + offset;")
    lines.append("        return slope * std::log10(s * mult + 1.0f) + offset;")
    lines.append("    }")

    # Canon Log 3 (v1.2)
    lines.append("    case LogCurve::Canon_Log_3: {")
    lines.append("        // Canon Log 3 (v1.2): three-segment curve")
    lines.append("        constexpr float slope = 0.36726845f;")
    lines.append("        constexpr float lin_slope = 1.9754798f;")
    lines.append("        constexpr float off_neg = 0.12783901f;")
    lines.append("        constexpr float off_lin = 0.12512219f;")
    lines.append("        constexpr float off_pos = 0.12240537f;")
    lines.append("        constexpr float mult = 14.98325f;")
    lines.append("        constexpr float thr_neg = 0.097465473f;")
    lines.append("        constexpr float thr_pos = 0.15277891f;")
    lines.append("        float s = x / 0.9f;")
    lines.append("        if (s < 0.0f) return -slope * std::log10(-s * mult + 1.0f) + off_neg;")
    lines.append("        float y = slope * std::log10(s * mult + 1.0f) + off_pos;")
    lines.append("        if (y > thr_pos) return y;")
    lines.append("        // Linear graft region")
    lines.append("        float y0 = slope * std::log10(0.0f * mult + 1.0f) + off_pos;")
    lines.append("        float x0 = (y0 - off_lin) / lin_slope;")
    lines.append("        if (s < x0) return off_neg;  // negative toe")
    lines.append("        return lin_slope * s + off_lin;")
    lines.append("    }")

    # S-Log3
    lines.append("    case LogCurve::S_Log3: {")
    lines.append("        // S-Log3")
    lines.append("        if (x >= 0.01125000f)")
    lines.append("            return (420.0f + 261.5f * std::log10((x + 0.01f) / 0.19f)) / 1023.0f;")
    lines.append("        return (x * (171.2102946929f - 95.0f) / 0.01125000f + 95.0f) / 1023.0f;")
    lines.append("    }")

    # Arri LogC3 (EI 800)
    lines.append("    case LogCurve::Arri_LogC3: {")
    lines.append("        // ARRI LogC3 (EI 800, Linear Scene Exposure Factor)")
    lines.append("        constexpr float cut = 0.010591f;")
    lines.append("        if (x > cut) return 0.247190f * std::log10(5.555556f * x + 0.052272f) + 0.385537f;")
    lines.append("        return 5.367655f * x + 0.092809f;")
    lines.append("    }")

    # Arri LogC4
    lines.append("    case LogCurve::Arri_LogC4: {")
    lines.append("        // ARRI LogC4")
    lines.append("        constexpr float a = (std::pow(2.0f, 18.0f) - 16.0f) / 117.45f;")
    lines.append("        constexpr float b = (1023.0f - 95.0f) / 1023.0f;")
    lines.append("        constexpr float c = 95.0f / 1023.0f;")
    lines.append("        constexpr float s_val = (7.0f * std::log(2.0f) * std::pow(2.0f, 7.0f - 14.0f*c/b)) / (a * b);")
    lines.append("        constexpr float t = (std::pow(2.0f, 14.0f*(-c/b) + 6.0f) - 64.0f) / a;")
    lines.append("        if (x >= t) return (std::log2(a * x + 64.0f) - 6.0f) / 14.0f * b + c;")
    lines.append("        return (x - t) / s_val;")
    lines.append("    }")

    # Log3G10
    lines.append("    case LogCurve::Log3G10: {")
    lines.append("        // RED Log3G10 (v3)")
    lines.append("        constexpr float a = 0.224282f;")
    lines.append("        constexpr float b = 155.975327f;")
    lines.append("        constexpr float c = 0.01f;")
    lines.append("        constexpr float g = 15.1927f;")
    lines.append("        float xs = x + c;")
    lines.append("        if (xs < 0.0f) return xs * g;")
    lines.append("        return a * std::log10(xs * b + 1.0f);")
    lines.append("    }")

    # D-Log
    lines.append("    case LogCurve::D_Log: {")
    lines.append("        // DJI D-Log")
    lines.append("        if (x <= 0.0078f) return 6.025f * x + 0.0929f;")
    lines.append("        return std::log10(x * 0.9892f + 0.0108f) * 0.256663f + 0.584555f;")
    lines.append("    }")

    # L-Log (BT.2020 with a custom curve — use S-Log3 as fallback for now, or implement separately)
    lines.append("    case LogCurve::L_Log: {")
    lines.append("        // L-Log: Leica log curve")
    lines.append("        // Uses ITU-R BT.2020 gamut; curve similar to a generic log")
    lines.append("        // Fallback: use Canon Log 2 style encoding")
    lines.append("        constexpr float slope = 0.24136077f;")
    lines.append("        constexpr float offset = 0.092864125f;")
    lines.append("        constexpr float mult = 87.09937546f;")
    lines.append("        if (x < 0.0f) return -slope * std::log10(-x * mult + 1.0f) + offset;")
    lines.append("        return slope * std::log10(x * mult + 1.0f) + offset;")
    lines.append("    }")

    lines.append("    default:")
    lines.append("        return x;  // passthrough")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("} // namespace rawalchemy")
    lines.append("")

    header = "\n".join(lines)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header)

    print(f"Generated: {output_path}")


def main():
    print("=== Computing Gamut Transform Matrices ===\n")
    matrices = compute_all_matrices()

    output_path = os.path.join(
        os.path.dirname(__file__), '..',
        'include', 'raw_alchemy', 'color_data.h'
    )
    generate_cpp_header(matrices, output_path)


if __name__ == "__main__":
    main()
