#pragma once
/**
 * @file color_data.h
 * @brief Pre-computed color space data for Raw Alchemy C++.
 *
 * AUTO-GENERATED by scripts/gen_color_data.py — DO NOT EDIT.
 * Gamut transform matrices: ProPhoto RGB -> Target Gamut (Linear)
 * Computed using colour-science matrix_RGB_to_RGB() with CAT02 adaptation.
 */

#include <array>
#include <cmath>
#include <string>
#include <unordered_map>

namespace rawalchemy {

// ============================================
//  Gamut Transform Matrices (3x3, row-major)
//  Source: ProPhoto RGB (Linear)
// ============================================

// ProPhoto RGB -> F-Gamut
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_F_GAMUT = {{
    {  1.20299289f,  -0.06586700f,  -0.13723735f},
    { -0.06714261f,   1.07233094f,  -0.00512774f},
    {  0.00401366f,  -0.02521870f,   1.02095013f},
}};

// ProPhoto RGB -> F-Gamut C
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_F_GAMUT_C = {{
    {  0.95908913f,   0.11425358f,  -0.07343251f},
    { -0.00343211f,   0.91079344f,   0.09265973f},
    {  0.00217947f,   0.00307289f,   0.99450087f},
}};

// ProPhoto RGB -> V-Gamut
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_V_GAMUT = {{
    {  1.11801084f,  -0.04944332f,  -0.06868460f},
    { -0.02619577f,   0.93091405f,   0.09530561f},
    {  0.01147910f,   0.00650952f,   0.98176588f},
}};

// ProPhoto RGB -> N-Gamut
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_N_GAMUT = {{
    {  1.20299289f,  -0.06586700f,  -0.13723735f},
    { -0.06714261f,   1.07233094f,  -0.00512774f},
    {  0.00401366f,  -0.02521870f,   1.02095013f},
}};

// ProPhoto RGB -> ITU-R BT.2020
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_ITU_R_BT_2020 = {{
    {  1.20299289f,  -0.06586700f,  -0.13723735f},
    { -0.06714261f,   1.07233094f,  -0.00512774f},
    {  0.00401366f,  -0.02521870f,   1.02095013f},
}};

// ProPhoto RGB -> Cinema Gamut
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_CINEMA_GAMUT = {{
    {  1.05715245f,  -0.02306629f,  -0.03420387f},
    { -0.00498024f,   0.84419113f,   0.16079025f},
    {  0.00855682f,   0.15185490f,   0.83938634f},
}};

// ProPhoto RGB -> S-Gamut3
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_S_GAMUT3 = {{
    {  1.07447750f,  -0.01057412f,  -0.06401515f},
    { -0.02509682f,   0.90395499f,   0.12115806f},
    {  0.01177883f,  -0.00083537f,   0.98880985f},
}};

// ProPhoto RGB -> S-Gamut3.Cine
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_S_GAMUT3_CINE = {{
    {  1.25551888f,  -0.17218155f,  -0.08347344f},
    {  0.00501517f,   0.84413504f,   0.15085221f},
    {  0.03723209f,   0.01843067f,   0.94409955f},
}};

// ProPhoto RGB -> ARRI Wide Gamut 3
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_ARRI_WIDE_GAMUT_3 = {{
    {  1.22360641f,  -0.14765486f,  -0.07608447f},
    { -0.10598340f,   0.91998001f,   0.18601326f},
    { -0.00707143f,   0.05673275f,   0.95010525f},
}};

// ProPhoto RGB -> ARRI Wide Gamut 4
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_ARRI_WIDE_GAMUT_4 = {{
    {  1.07456609f,  -0.01374909f,  -0.06092970f},
    { -0.00343278f,   0.91090200f,   0.09255187f},
    {  0.00217947f,   0.00307289f,   0.99450087f},
}};

// ProPhoto RGB -> REDWideGamutRGB
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_REDWIDEGAMUTRGB = {{
    {  1.02138791f,   0.02756710f,  -0.04906104f},
    { -0.01834546f,   0.86171893f,   0.15663064f},
    {  0.05104381f,   0.20108092f,   0.74769320f},
}};

// ProPhoto RGB -> DJI D-Gamut
constexpr std::array<std::array<float, 3>, 3> MAT_PROPHOTO_TO_DJI_D_GAMUT = {{
    {  1.18948816f,  -0.11830996f,  -0.07127751f},
    { -0.07933702f,   0.91984670f,   0.15943608f},
    {  0.01470437f,   0.06523829f,   0.92000454f},
}};

// ============================================
//  Log Space Registry
//  Maps log space name -> {gamut_matrix, curve_name}
// ============================================

enum class LogCurve {
    Arri_LogC3,
    Arri_LogC4,
    Canon_Log_2,
    Canon_Log_3,
    D_Log,
    F_Log,
    F_Log2,
    L_Log,
    Log3G10,
    N_Log,
    S_Log3,
    V_Log
};

struct LogSpaceInfo {
    const std::array<std::array<float, 3>, 3>* gamutMatrix;
    LogCurve curve;
    const char* name;
};

// Lookup table: log space name -> info
const std::unordered_map<std::string, LogSpaceInfo> LOG_SPACES = {
    {"F-Log", {&MAT_PROPHOTO_TO_F_GAMUT, LogCurve::F_Log, "F-Log"}},
    {"F-Log2", {&MAT_PROPHOTO_TO_F_GAMUT, LogCurve::F_Log2, "F-Log2"}},
    {"F-Log2C", {&MAT_PROPHOTO_TO_F_GAMUT_C, LogCurve::F_Log2, "F-Log2C"}},
    {"V-Log", {&MAT_PROPHOTO_TO_V_GAMUT, LogCurve::V_Log, "V-Log"}},
    {"N-Log", {&MAT_PROPHOTO_TO_N_GAMUT, LogCurve::N_Log, "N-Log"}},
    {"L-Log", {&MAT_PROPHOTO_TO_ITU_R_BT_2020, LogCurve::L_Log, "L-Log"}},
    {"Canon Log 2", {&MAT_PROPHOTO_TO_CINEMA_GAMUT, LogCurve::Canon_Log_2, "Canon Log 2"}},
    {"Canon Log 3", {&MAT_PROPHOTO_TO_CINEMA_GAMUT, LogCurve::Canon_Log_3, "Canon Log 3"}},
    {"S-Log3", {&MAT_PROPHOTO_TO_S_GAMUT3, LogCurve::S_Log3, "S-Log3"}},
    {"S-Log3.Cine", {&MAT_PROPHOTO_TO_S_GAMUT3_CINE, LogCurve::S_Log3, "S-Log3.Cine"}},
    {"Arri LogC3", {&MAT_PROPHOTO_TO_ARRI_WIDE_GAMUT_3, LogCurve::Arri_LogC3, "Arri LogC3"}},
    {"Arri LogC4", {&MAT_PROPHOTO_TO_ARRI_WIDE_GAMUT_4, LogCurve::Arri_LogC4, "Arri LogC4"}},
    {"Log3G10", {&MAT_PROPHOTO_TO_REDWIDEGAMUTRGB, LogCurve::Log3G10, "Log3G10"}},
    {"D-Log", {&MAT_PROPHOTO_TO_DJI_D_GAMUT, LogCurve::D_Log, "D-Log"}},
};

// ============================================
//  Log Curve Encoding Functions (Linear -> Log)
//  All operate on a single float value in [0, inf)
// ============================================

inline float logEncode(float x, LogCurve curve) {
    switch (curve) {
    case LogCurve::F_Log: {
        // F-Log: cut=0.00089, a=0.555556, b=0.009468, c=0.344676, d=0.790453, e=8.735631, f=0.092864
        constexpr float cut = 0.00089f;
        if (x < cut) return 8.735631f * x + 0.092864f;
        return 0.344676f * std::log10(0.555556f * x + 0.009468f) + 0.790453f;
    }
    case LogCurve::F_Log2: {
        // F-Log2: cut=0.000889, a=5.555556, b=0.064829, c=0.245281, d=0.384316, e=8.799461, f=0.092864
        constexpr float cut = 0.000889f;
        if (x < cut) return 8.799461f * x + 0.092864f;
        return 0.245281f * std::log10(5.555556f * x + 0.064829f) + 0.384316f;
    }
    case LogCurve::V_Log: {
        // V-Log: cut=0.01, b=0.00873, c=0.241514, d=0.598206
        if (x < 0.01f) return 5.6f * x + 0.125f;
        return 0.241514f * std::log10(x + 0.00873f) + 0.598206f;
    }
    case LogCurve::N_Log: {
        // N-Log: a=650/1023, b=0.0075, c=150/1023, d=619/1023, cut=0.328
        constexpr float a = 650.0f / 1023.0f;
        constexpr float b = 0.0075f;
        constexpr float c = 150.0f / 1023.0f;
        constexpr float d = 619.0f / 1023.0f;
        constexpr float cut = 0.328f;
        if (x < cut) return a * std::cbrt(x + b);
        return c * std::log(x) + d;
    }
    case LogCurve::Canon_Log_2: {
        // Canon Log 2 (v1.2): slope=0.24136077, offset=0.092864125, mult=87.09937546
        constexpr float slope = 0.24136077f;
        constexpr float offset = 0.092864125f;
        constexpr float mult = 87.09937546f;
        float s = x / 0.9f;  // reflection to scene-linear
        if (s < 0.0f) return -slope * std::log10(-s * mult + 1.0f) + offset;
        return slope * std::log10(s * mult + 1.0f) + offset;
    }
    case LogCurve::Canon_Log_3: {
        // Canon Log 3 (v1.2): three-segment curve
        constexpr float slope = 0.36726845f;
        constexpr float lin_slope = 1.9754798f;
        constexpr float off_neg = 0.12783901f;
        constexpr float off_lin = 0.12512219f;
        constexpr float off_pos = 0.12240537f;
        constexpr float mult = 14.98325f;
        constexpr float thr_pos = 0.15277891f;
        float s = x / 0.9f;
        if (s < 0.0f) return -slope * std::log10(-s * mult + 1.0f) + off_neg;
        float y = slope * std::log10(s * mult + 1.0f) + off_pos;
        if (y > thr_pos) return y;
        // Linear graft region
        float y0 = slope * std::log10(0.0f * mult + 1.0f) + off_pos;
        float x0 = (y0 - off_lin) / lin_slope;
        if (s < x0) return off_neg;  // negative toe
        return lin_slope * s + off_lin;
    }
    case LogCurve::S_Log3: {
        // S-Log3
        if (x >= 0.01125000f)
            return (420.0f + 261.5f * std::log10((x + 0.01f) / 0.19f)) / 1023.0f;
        return (x * (171.2102946929f - 95.0f) / 0.01125000f + 95.0f) / 1023.0f;
    }
    case LogCurve::Arri_LogC3: {
        // ARRI LogC3 (EI 800, Linear Scene Exposure Factor)
        constexpr float cut = 0.010591f;
        if (x > cut) return 0.247190f * std::log10(5.555556f * x + 0.052272f) + 0.385537f;
        return 5.367655f * x + 0.092809f;
    }
    case LogCurve::Arri_LogC4: {
        // ARRI LogC4
        const float a = (std::pow(2.0f, 18.0f) - 16.0f) / 117.45f;
        const float b = (1023.0f - 95.0f) / 1023.0f;
        const float c = 95.0f / 1023.0f;
        const float s_val = (7.0f * std::log(2.0f) * std::pow(2.0f, 7.0f - 14.0f*c/b)) / (a * b);
        const float t = (std::pow(2.0f, 14.0f*(-c/b) + 6.0f) - 64.0f) / a;
        if (x >= t) return (std::log2(a * x + 64.0f) - 6.0f) / 14.0f * b + c;
        return (x - t) / s_val;
    }
    case LogCurve::Log3G10: {
        // RED Log3G10 (v3)
        constexpr float a = 0.224282f;
        constexpr float b = 155.975327f;
        constexpr float c = 0.01f;
        constexpr float g = 15.1927f;
        float xs = x + c;
        if (xs < 0.0f) return xs * g;
        return a * std::log10(xs * b + 1.0f);
    }
    case LogCurve::D_Log: {
        // DJI D-Log
        if (x <= 0.0078f) return 6.025f * x + 0.0929f;
        return std::log10(x * 0.9892f + 0.0108f) * 0.256663f + 0.584555f;
    }
    case LogCurve::L_Log: {
        // L-Log: Leica log curve
        // Uses ITU-R BT.2020 gamut; curve similar to a generic log
        // Fallback: use Canon Log 2 style encoding
        constexpr float slope = 0.24136077f;
        constexpr float offset = 0.092864125f;
        constexpr float mult = 87.09937546f;
        if (x < 0.0f) return -slope * std::log10(-x * mult + 1.0f) + offset;
        return slope * std::log10(x * mult + 1.0f) + offset;
    }
    default:
        return x;  // passthrough
    }
}

} // namespace rawalchemy
